# Generated by Django 4.1.7 on 2023-02-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversations",
            name="response_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
